### ISSUE TITLE
404 returned on https://devsnippets.xyz/snippets/welcome

### ISSUE THREAD

**Issue by Crammers** [rickwest/devsnippets#30]
Hi Rick, I thought I'd check out the devsnippets site, looks like the to the snippets button sends us to a 404. Had a look around the source but not too familiar with how the pages are built. I take it might be related to the name change of getting started to welcome?

**Comment by rickwest** [comment]
Cheers Craig, thanks for the heads up! Looks like the file was renamed in a PR that I merged yesterday. Sorted now. That will tech me to not get over zealous with the merge button in future!
