### ISSUE TITLE
Make js snippets more consistent and fix typos/grammatical issues

### ISSUE THREAD

**Issue by janelbrandon** [rickwest/devsnippets#44]
Hi Rick - I just want to offer to introduce some consistency in the javascript snippets md, if that's something you would want done. I don't want to step on toes :)

If there's a style guide you'd like followed, let me know, or an example you'd like to use as a guide.

**Comment by rickwest** [comment]
Hey Janel!

Your offer is gratefully accepted! That would be great, as it is getting very disorganised! 

With the influx of Hacktoberfest PR's, I've just been concentrating on getting thing's merged, with the intent to come back and clean everything up at some point down the line, so you're help with this would be greatly appreciated!

There is no style guide that is enforced yet (as JavaScript isn't really my primary language, so I don't know what's best 🤷‍♂️), therefore if you want to encourage something appropriate then that would be awesome. Once tidied up, if you can add something regarding desired style in the README.md for future contributors that would be ideal!

**Comment by janelbrandon** [comment]
This was fun! Thanks 😊
